# Generated by Django 2.2.12 on 2020-12-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0011_auto_20201218_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='sewa',
            name='sewa',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sewa',
            name='tujuan',
            field=models.CharField(max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='sewa',
            name='waktu',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
