# Generated by Django 2.2.12 on 2020-12-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sewa', '0015_auto_20201223_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sewa',
            name='nama_pemesan',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
