# Generated by Django 2.2 on 2020-12-25 06:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default=None, max_length=100)),
                ('merk_seri_bus', models.CharField(choices=[('Scania', 'Scania'), ('Hino', 'Hino'), ('Mercedez Benz', 'Mercedez Benz'), ('Volvo', 'Volvo'), ('Mitsubishi Fuso', 'Mitsubishi Fuso'), ('Toyota Dyana', 'Toyota Dyana'), ('Zhong Thong', 'Zhong Thong')], default=None, max_length=100, null=True)),
                ('tahun_pembuatan', models.IntegerField(default=2015)),
                ('no_plat', models.CharField(default=None, max_length=15)),
                ('kategori', models.CharField(choices=[('kecil', 'Kecil'), ('medium', 'Medium'), ('besar', 'Besar')], default=None, max_length=10, null=True)),
                ('harga_12jam', models.IntegerField(default=500000)),
                ('harga_fullday', models.IntegerField(default=1000000)),
                ('jml_kursi', models.IntegerField(default=None)),
                ('jml_bus', models.IntegerField(default=None)),
                ('ac', models.BooleanField(default=False, verbose_name='ac')),
                ('dvd', models.BooleanField(default=False, verbose_name='DVD/Video')),
                ('toilet', models.BooleanField(default=False, verbose_name='Toilet')),
                ('stop_kontak', models.BooleanField(default=False, verbose_name='Stop Kontak')),
                ('sabuk_pengaman', models.BooleanField(default=False, verbose_name='Sabuk Pengaman')),
                ('bagasi', models.BooleanField(default=False, verbose_name='Bagasi')),
                ('wifi', models.BooleanField(default=False, verbose_name='WIFI')),
                ('tv', models.BooleanField(default=False, verbose_name='TV')),
                ('bantal', models.BooleanField(default=False, verbose_name='Bantal')),
                ('selimut', models.BooleanField(default=False, verbose_name='Selimut')),
                ('smoking_area', models.BooleanField(default=False, verbose_name='Smoking Area')),
                ('tambahan', models.TextField(default=None, null=True)),
                ('po_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='po_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hotel_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_perusahaan', models.CharField(default=None, max_length=100)),
                ('foto_profil', models.ImageField(blank=True, upload_to='gambar/')),
                ('tanggal_berdiri', models.DateField()),
                ('no_tlpn', models.CharField(blank=True, default=False, max_length=15)),
                ('no_hp', models.CharField(default=62, max_length=15)),
                ('email', models.EmailField(default=None, max_length=254, null=True)),
                ('provinsi', models.CharField(default=False, max_length=50)),
                ('kabupaten_kota', models.CharField(default=False, max_length=15)),
                ('kecamatan', models.CharField(default=False, max_length=50)),
                ('kode_pos', models.IntegerField(default=False)),
                ('alamat_lengkap', models.TextField(default=None, null=True)),
                ('bio', models.TextField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gambar/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pengguna.DataBus')),
            ],
        ),
    ]
