# Generated by Django 2.2 on 2021-01-05 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='alamat_lengkap',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='foto_profil',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='kabupaten_kota',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='kecamatan',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='kode_pos',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='no_hp',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='no_tlpn',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='provinsi',
        ),
        migrations.RemoveField(
            model_name='profil',
            name='tanggal_berdiri',
        ),
    ]
