# Generated by Django 2.2 on 2021-01-05 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pengguna', '0002_auto_20210105_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='alamat_lengkap',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='bio',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='profil',
            name='email',
            field=models.EmailField(default=None, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='foto_profil',
            field=models.ImageField(blank=True, upload_to='gambar/'),
        ),
        migrations.AddField(
            model_name='profil',
            name='no_hp',
            field=models.CharField(default=62, max_length=15),
        ),
        migrations.AddField(
            model_name='profil',
            name='tanggal_berdiri',
            field=models.DateField(null=True),
        ),
    ]
